# Generated by Django 5.2.6 on 2025-10-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstem4girls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mujeres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
