# Generated by Django 5.2.6 on 2025-11-04 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstem4girls', '0002_mujeres_proveedor_ciudad_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mujeres',
            name='fecha_NCTO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mujeres',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mujer_proveedor', to='appstem4girls.proveedor'),
        ),
    ]
