# Generated by Django 5.2.6 on 2025-11-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstem4girls', '0004_recurso_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Image'),
        ),
    ]
