# Generated by Django 5.2.6 on 2025-11-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstem4girls', '0005_alter_recurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#9272DC', max_length=7),
        ),
    ]
