# Generated by Django 5.2.6 on 2025-11-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appstem4girls', '0006_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.AddField(
            model_name='tag',
            name='color_class',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
